apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: z54jt6ann-nodejs 
  janus-idp.io/tekton: z54jt6ann-nodejs
  backstage.io/kubernetes-id: z54jt6ann-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z54jt6ann-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  