apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: z54jt6ann-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: z54jt6ann-nodejs 
  name: z54jt6ann-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: z54jt6ann-nodejs 
